"""Adding recommends column

Revision ID: 28c95427362c
Revises: 54860f8bdc72
Create Date: 2018-02-16 07:52:46.091744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c95427362c'
down_revision = '54860f8bdc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('recommend_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'recommends', ['recommend_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'recommend_id')
    # ### end Alembic commands ###
