"""Edited user model to allow anyone to post

Revision ID: 71b7bc3d6dfa
Revises: 1f6af82de5ff
Create Date: 2018-02-14 16:14:11.363923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b7bc3d6dfa'
down_revision = '1f6af82de5ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reports_community_id_fkey', 'reports', type_='foreignkey')
    op.drop_column('reports', 'community_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('community_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('reports_community_id_fkey', 'reports', 'community_members', ['community_id'], ['id'])
    # ### end Alembic commands ###
