"""Edited models about to do ui

Revision ID: dc52a84536d9
Revises: 71b7bc3d6dfa
Create Date: 2018-02-15 10:47:48.805125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc52a84536d9'
down_revision = '71b7bc3d6dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('verification', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'verification')
    # ### end Alembic commands ###
